const ImageData = {
  "All Projects": [
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 1 ·",
    },
    {
      src: "/background/1.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 2 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 3 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 4 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 5 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 7 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 16 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 17 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 22 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 23 ·",
    },
  ],
  Shoes: [
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 2 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 8 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 18 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 24 ·",
    },
  ],
  Bags: [
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 6 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 10 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 14 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 19 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 25 ·",
    },
  ],
  Electronics: [
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 9 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 10 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 11 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 20 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 26 ·",
    },
  ],
  Gaming: [
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 12 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 13 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 15 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 21 ·",
    },
    {
      src: "/portfolio/cfsi.jpg",
      githubUrl: "https://github.com/user/repository",
      liveUrl: "https://live-site-link.com",
      title: "CFSI SHS LOGO",
      description: "Random Description 27 ·",
    },
  ],
};

export default ImageData;
